// http api call
POST  http://localhost:8080/events
Content-Type: application/json

{
    "name": "Event 1",
    "description": "Event 1 Description",
    "location": "Event 1 Location",
    "time": "2021-01-01T00:00:00.000Z"
}


# {"name": "Event 1'; DROP TABLE events; --", "description": "Test", "location": "Test Location", "time": "2021-01-01T00:00:00.000Z"}
